defaults: &defaults
  steps:
     - checkout

     ## docker-compose for Redash -----------
     - run:
         name: Install Docker Compose
         command: |
           set -x
           wget -O - https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
           chmod +x /usr/local/bin/docker-compose
     - setup_remote_docker
     - run: wget -O - https://github.com/getredash/redash/archive/v2.0.0.tar.gz | tar -xzf -
     - run: (cd redash-2.0.0; docker-compose -f docker-compose.production.yml run --rm server create_db)

     ## setup -------------------------------

     - run:
         name: Set environmental variables
         command: |
           Rscript --vanilla \
             -e 'dsc <- read.dcf("DESCRIPTION")' \
             -e 'cat(sprintf("export PKG_TARBALL=%s_%s.tar.gz\n", dsc[,"Package"], dsc[,"Version"]))' \
             -e 'cat(sprintf("export RCHECK_DIR=%s.Rcheck\n", dsc[,"Package"]))' \
             >> ${BASH_ENV}

     ## install dependencies ------------------

     - run: Rscript -e 'if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")'
     - run: Rscript -e 'devtools::install_deps(dependencies = TRUE)'

     ## build and test -----------------

     - run: R CMD build .
     - run: R CMD check "${PKG_TARBALL}" --as-cran --no-manual
     - run: Rscript -e "message(devtools::check_failures(path = '${RCHECK_DIR}'))"
     # warnings are errors
     # - run: if grep -q -R "WARNING" "${RCHECK_DIR}/00check.log"; then exit 1; fi

     ## store artifacts -----------------

     - run:
         command: mv ${RCHECK_DIR} /tmp/Rcheck
         when: always
     - store_artifacts:
         path: /tmp/Rcheck
         when: always

version: 2
jobs:
   "r-release":
     docker:
       - image: rocker/tidyverse:latest
     <<: *defaults

   "r-devel":
     docker:
       - image: rocker/tidyverse:devel
     <<: *defaults

workflows:
  version: 2
  build_and_test:
    jobs:
      - "r-release"
      # - "r-devel"
