defaults: &defaults
  steps:
     ## setup -------------------------------

     - checkout
     - run:
         name: Set environmental variables
         command: |
           Rscript --vanilla \
             -e 'dsc <- read.dcf("DESCRIPTION")' \
             -e 'cat(sprintf("export PKG_TARBALL=%s_%s.tar.gz\n", dsc[,"Package"], dsc[,"Version"]))' \
             -e 'cat(sprintf("export RCHECK_DIR=%s.Rcheck\n", dsc[,"Package"]))' \
             >> ${BASH_ENV}

     ## install dependencies ------------------

     - run: Rscript -e 'if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")'
     - run: Rscript -e 'devtools::install_deps(dependencies = TRUE)'

     ## build and test -----------------

     - run: R CMD build .
     - run: R CMD check "${PKG_TARBALL}" --as-cran --no-manual
     - run: Rscript -e "message(devtools::check_failures(path = '${RCHECK_DIR}'))"
     # warnings are errors
     # - run: if grep -q -R "WARNING" "${RCHECK_DIR}/00check.log"; then exit 1; fi

     ## store artifacts -----------------

     - run:
         command: mv ${RCHECK_DIR} /tmp/Rcheck
         when: always
     - store_artifacts:
         path: /tmp/Rcheck
         when: always

version: 2
jobs:
   "r-release":
     docker:
       - image: rocker/tidyverse:latest

       - image: redash/redash:latest
         entrypoint: server
         environment:
           PYTHONUNBUFFERED: 0
           REDASH_LOG_LEVEL: "INFO"
           REDASH_REDIS_URL: "redis://redis:6379/0"
           REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
           REDASH_COOKIE_SECRET: veryverysecret
           REDASH_WEB_WORKERS: 4

       - image: redash/redash:latest
         entrypoint: scheduler
         environment:
           PYTHONUNBUFFERED: 0
           REDASH_LOG_LEVEL: "INFO"
           REDASH_REDIS_URL: "redis://redis:6379/0"
           REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
           QUEUES: "queries,scheduled_queries,celery"
           WORKERS_COUNT: 2

       - image: redis:3.0-alpine

       - image: postgres:9.5.6-alpine

       - image: redash/nginx:latest
     <<: *defaults

   "r-devel":
     docker:
       - image: rocker/tidyverse:devel
     <<: *defaults

workflows:
  version: 2
  build_and_test:
    jobs:
      - "r-release"
      # - "r-devel"
